export const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS app_state (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS operator_profiles (
    operator_name TEXT NOT NULL,
    operator_code TEXT NOT NULL,
    role TEXT NOT NULL,
    task_type TEXT NOT NULL DEFAULT 'packing',
    full_name TEXT,
    last_used_at TEXT NOT NULL,
    password_salt TEXT,
    password_hash TEXT,
    PRIMARY KEY (operator_name, operator_code, role)
  )`,
  `CREATE TABLE IF NOT EXISTS operator_sessions (
    session_id TEXT PRIMARY KEY NOT NULL,
    operator_name TEXT NOT NULL,
    operator_code TEXT NOT NULL,
    role TEXT NOT NULL,
    task_type TEXT NOT NULL DEFAULT 'packing',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS recordings (
    id TEXT PRIMARY KEY NOT NULL,
    resi_number TEXT NOT NULL,
    task_type TEXT NOT NULL DEFAULT 'packing',
    operator_name TEXT,
    operator_code TEXT,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    media_type TEXT NOT NULL DEFAULT 'video',
    mime_type TEXT,
    file_size_bytes INTEGER,
    record_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT,
    duration_seconds INTEGER,
    status TEXT NOT NULL,
    note TEXT,
    packing_session_id TEXT,
    packer_operator_name TEXT,
    packer_operator_code TEXT,
    order_number TEXT,
    shipping_channel TEXT,
    order_snapshot TEXT,
    packing_pay_amount INTEGER,
    packing_pay_status TEXT,
    packing_pay_breakdown TEXT,
    packing_pay_rule_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_recordings_resi_number ON recordings (resi_number)`,
  `CREATE INDEX IF NOT EXISTS idx_recordings_status ON recordings (status)`,
  `CREATE INDEX IF NOT EXISTS idx_recordings_packing_session_id ON recordings (packing_session_id)`,
  `CREATE INDEX IF NOT EXISTS idx_recordings_start_time ON recordings (start_time DESC)`,
  `CREATE TABLE IF NOT EXISTS packing_work_sessions (
    id TEXT PRIMARY KEY NOT NULL,
    packer_operator_name TEXT NOT NULL,
    packer_operator_code TEXT NOT NULL,
    packer_name_snapshot TEXT NOT NULL,
    packer_code_snapshot TEXT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    status TEXT NOT NULL,
    note TEXT,
    created_by_session_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_packing_work_sessions_status ON packing_work_sessions (status)`,
  `CREATE INDEX IF NOT EXISTS idx_packing_work_sessions_started_at ON packing_work_sessions (started_at DESC)`,
  `CREATE TABLE IF NOT EXISTS packing_pay_rules (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    match_type TEXT NOT NULL,
    match_value TEXT,
    pay_type TEXT NOT NULL,
    amount INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_packing_pay_rules_priority ON packing_pay_rules (priority DESC)`,
  `CREATE TABLE IF NOT EXISTS packing_payments (
    id TEXT PRIMARY KEY NOT NULL,
    payment_no TEXT NOT NULL,
    packer_operator_name TEXT NOT NULL,
    packer_operator_code TEXT NOT NULL,
    packer_name_snapshot TEXT NOT NULL,
    packer_code_snapshot TEXT NOT NULL,
    total_sessions INTEGER NOT NULL,
    total_packages INTEGER NOT NULL,
    total_amount INTEGER NOT NULL,
    payment_method TEXT NOT NULL,
    paid_at TEXT NOT NULL,
    paid_by_operator_name TEXT NOT NULL,
    paid_by_operator_code TEXT NOT NULL,
    paid_by_session_id TEXT,
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_packing_payments_paid_at ON packing_payments (paid_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_packing_payments_packer ON packing_payments (packer_operator_code)`,
  `CREATE TABLE IF NOT EXISTS scan_logs (
    id TEXT PRIMARY KEY NOT NULL,
    resi_number TEXT NOT NULL,
    task_type TEXT NOT NULL DEFAULT 'packing',
    operator_name TEXT,
    operator_code TEXT,
    scan_time TEXT NOT NULL,
    action TEXT NOT NULL,
    message TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_scan_logs_scan_time ON scan_logs (scan_time DESC)`,
  `CREATE TABLE IF NOT EXISTS system_config (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS bootstrap_state (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS last_error (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY NOT NULL,
    source TEXT NOT NULL,
    order_number TEXT NOT NULL,
    tracking_number TEXT,
    buyer_username TEXT,
    shipping_channel TEXT,
    order_status TEXT,
    raw_payload TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(source, order_number)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_orders_tracking_number ON orders (tracking_number)`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id TEXT PRIMARY KEY NOT NULL,
    order_id TEXT NOT NULL,
    sku TEXT,
    product_name TEXT NOT NULL,
    variation_name TEXT,
    quantity INTEGER NOT NULL,
    image_url TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id)`,
  `CREATE TABLE IF NOT EXISTS recording_chat_sends (
    id TEXT PRIMARY KEY NOT NULL,
    recording_id TEXT NOT NULL,
    order_id TEXT,
    resi_number TEXT NOT NULL,
    order_number TEXT,
    buyer_username TEXT NOT NULL,
    task_type TEXT NOT NULL,
    video_file_path TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    message_template TEXT,
    error_message TEXT,
    prepared_at TEXT,
    sent_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(recording_id, buyer_username)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_recording_chat_sends_recording_id ON recording_chat_sends (recording_id)`,
  `CREATE INDEX IF NOT EXISTS idx_recording_chat_sends_status ON recording_chat_sends (status)`,
  `CREATE INDEX IF NOT EXISTS idx_recording_chat_sends_buyer_username ON recording_chat_sends (buyer_username)`,
  `CREATE INDEX IF NOT EXISTS idx_recording_chat_sends_resi_number ON recording_chat_sends (resi_number)`,
  `CREATE TABLE IF NOT EXISTS shipping_chat_sends (
    id TEXT PRIMARY KEY NOT NULL,
    order_id TEXT NOT NULL,
    order_number TEXT NOT NULL,
    tracking_number TEXT,
    buyer_username TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    prepared_at TEXT,
    sent_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(order_number, buyer_username),
    FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_shipping_chat_sends_order_number ON shipping_chat_sends (order_number)`,
  `CREATE INDEX IF NOT EXISTS idx_shipping_chat_sends_status ON shipping_chat_sends (status)`,
  `CREATE INDEX IF NOT EXISTS idx_shipping_chat_sends_buyer_username ON shipping_chat_sends (buyer_username)`,
] as const
